### ISSUE TITLE
[FR] configure network interfaces

### ISSUE THREAD

**Issue by anubister** [YunoHost-Apps/monitorix_ynh#20]
Currently the default configuration file guesses only one network interface `eth0` in https://github.com/YunoHost-Apps/monitorix_ynh/blob/master/conf/monitorix.conf#L309 ; it could be nice to configure it automatically with the real interfaces of the system.
Nota : both <net> and <tc> sections has to be updated.

**Comment by Josue-T** [comment]
Hello,

Well, it's really a big job to generate a configuration for all configuration, because sometime there are many interface and we never know exactly what the user want. So it's why there are only some basic configuration and after the user need to customize as he want. But you still can make a PR to improve this.

**Comment by Josue-T** [comment]
Done by #55
